dist: bionic

language: r

r:
  - devel
  - release

sudo: false

cache: packages

r_check_args: --as-cran

addons:
  apt:
    packages:
      - ghostscript

r_packages:
  - covr
  - ggplot2
  - AER
  - bife
  - biglm
  - brms
  - btergm
  - censReg
  - dynlm
  - feisr
  - forecast
  - gamlss
  - gamlss.inf
  - glmmTMB
  - lfe
  - lme4
  - MASS
  - miceadds
  - mlogit
  - mnlogit
  - MuMIn
  - nlme
  - nnet
  - ordinal
  - VGAM
  - alpaca

notifications:
  email:
    recipients:
      - philip.leifeld@essex.ac.uk
      - claudia.zucca@glasgow.ac.uk
    on_success: change
    on_failure: change

after_success:
   - Rscript -e 'library(covr); codecov()'
